--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Shelly7w7/TotemJoin
build-by-default: true
branches:
- master
projects:
  TotemJoin:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
